Loading important libraries

In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding,LSTM,Flatten
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [2]:
text = ['Well done!',
 'Good work',
 'Great effort',
 'nice work',
 'Excellent!',
 'Weak',
 'Poor effort!',
 'not good',
 'poor work',
 'Could have done better']

In [3]:
text

['Well done!',
 'Good work',
 'Great effort',
 'nice work',
 'Excellent!',
 'Weak',
 'Poor effort!',
 'not good',
 'poor work',
 'Could have done better']

In [4]:
#ohe_hot_representation
vocal_length = 10000
one_hot_rep = [one_hot(word,vocal_length) for word in text]
one_hot_rep

[[556, 3397],
 [1455, 8276],
 [9921, 809],
 [826, 8276],
 [4696],
 [1121],
 [2634, 809],
 [5074, 1455],
 [2634, 8276],
 [3174, 3729, 3397, 7795]]

In [5]:
#padding
sent_length = 6
text_padd = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
text_padd

array([[   0,    0,    0,    0,  556, 3397],
       [   0,    0,    0,    0, 1455, 8276],
       [   0,    0,    0,    0, 9921,  809],
       [   0,    0,    0,    0,  826, 8276],
       [   0,    0,    0,    0,    0, 4696],
       [   0,    0,    0,    0,    0, 1121],
       [   0,    0,    0,    0, 2634,  809],
       [   0,    0,    0,    0, 5074, 1455],
       [   0,    0,    0,    0, 2634, 8276],
       [   0,    0, 3174, 3729, 3397, 7795]], dtype=int32)

In [6]:
#Ebedding---
model = Sequential()
model.add(Embedding(vocal_length,5,input_length = sent_length))
model.compile('adam','mse')

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 6, 5)              50000     
                                                                 
Total params: 50,000
Trainable params: 50,000
Non-trainable params: 0
_________________________________________________________________


-----------------------------------------------------------------------------------------------------------

# Apply models

In [8]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding,Flatten,Dense
from tensorflow.keras.models import Sequential
import numpy as np
import pandas as pd

In [9]:
sentences = ['Well done!',
 'Good work',
 'Great effort',
 'nice work',
 'Excellent!',
 'Weak',
 'Poor effort!',
 'not good',
 'poor work',
 'Could have done better']
labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [10]:
sentences

['Well done!',
 'Good work',
 'Great effort',
 'nice work',
 'Excellent!',
 'Weak',
 'Poor effort!',
 'not good',
 'poor work',
 'Could have done better']

In [11]:
labels

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [12]:
#one_hot_represent---
vocab_len = 50
sent_one = [one_hot(word,vocab_len) for word in sentences]
sent_one

[[48, 49],
 [2, 39],
 [25, 6],
 [49, 39],
 [2],
 [13],
 [9, 6],
 [23, 2],
 [9, 39],
 [48, 20, 49, 38]]

In [13]:
#padding----
sent_len = 4
sent_pad = pad_sequences(sent_one,padding='pre',maxlen=sent_len)
sent_pad

array([[ 0,  0, 48, 49],
       [ 0,  0,  2, 39],
       [ 0,  0, 25,  6],
       [ 0,  0, 49, 39],
       [ 0,  0,  0,  2],
       [ 0,  0,  0, 13],
       [ 0,  0,  9,  6],
       [ 0,  0, 23,  2],
       [ 0,  0,  9, 39],
       [48, 20, 49, 38]], dtype=int32)

In [14]:
#Word_embedding----
m = Sequential()
m.add(Embedding(vocab_len,8,input_length=sent_len))
m.add(Flatten())
m.add(Dense(1,activation='sigmoid'))
m.compile('adam','binary_crossentropy',metrics=['accuracy'])
m.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________


In [15]:
m.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________


In [16]:
#fikt the model--
m.fit(sent_pad,labels,epochs=50,verbose=0)
#evulate the model--
loss,accuracy = m.evaluate(sent_pad,labels,verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 80.000001


In [17]:
print('loss:',loss)

loss: 0.6399936676025391


In [18]:
accuracy

0.800000011920929